apiVersion: v1
kind: Service
metadata:
  name: besu-validator1-udp
  labels:
    app: validator1
  namespace: besu
spec:
  type: LoadBalancer
  selector:
    app: validator1
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
