apiVersion: v1
kind: Service
metadata:
  name: besu-node-udp
  labels:
    app: node
  namespace: besu
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
